### ISSUE TITLE
Research Authentication

### ISSUE THREAD

**Issue by kokhouser** [kokhouser/geothing#2]
It's clear we need to provide user authentication (username/password? Google account? Facebook? Twitter?) of some sort, so we can ensure that only authorized users can create Geocaches under their names.

Task: Research authentication frameworks that work with NodeJS and Express.

Or do we want to write our own?

**Comment by jtkilleen** [comment]
I saw that Express already allows implementation of [basic auth](http://blog.modulus.io/nodejs-and-express-basic-authentication). I'm currently looking into this option for now.

**Comment by kokhouser** [comment]
I suppose it would be best if we had a token generated for a set amount of time after authentication so users can pass that in? I don't really know how we want to do it.

**Comment by kokhouser** [comment]
@jtkilleen added authentication.

Closing this.
